version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  vdt-banco-de-dados-testes:
    secure: ggnWFrCFYUyrvD+MQuymcLS0p/E15V1qYJ/mSh6KJIQ=
  vdt-string-conexao-testes:
    secure: pZxBKcuTkC2DMElcMW1wpbuRKSERSlge8SUtf1PY/CAySF5+E6WF3rF4Y6/Z4i14GY5HwFeQBD1Im+ForReZCe8oJ7xLJyjc7pTAN8JrWSGrdR7WbrFjQVlA3/vQu33g2BNLRLo6H7ll6gFG2TT3fg==
  COVERALLS_REPO_TOKEN:
    secure: 1pEehKZ9pOnrg3Ourxfwa7bjGYyVUR5McWlgjQ5W36ZWnEBCjqkuTBXHHdrNM+is
before_build:
  - nuget restore ".\Server\src\Palla.Labs.Vdt.sln"
build:
  project: .\Server\src\Palla.Labs.Vdt.sln
  publish_wap_xcopy: true
  verbosity: normal
test_script:
- ps: >-
    nunit3-console "Server\src\Palla.Labs.Vdt.WebApi.Testes\bin\$env:CONFIGURATION\Palla.Labs.Vdt.WebApi.Testes.dll" --result=myresults.xml
- ps: >-
    .\Server\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""Server\src\Palla.Labs.Vdt.WebApi.Testes\bin\$env:CONFIGURATION\Palla.Labs.Vdt.WebApi.Testes.dll""" -filter:"+[Palla*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "Server\src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\myresults.xml))
deploy:
- provider: Environment
  name: Palla.Labs.Vdt.WebApi