version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 1pEehKZ9pOnrg3Ourxfwa7bjGYyVUR5McWlgjQ5W36ZWnEBCjqkuTBXHHdrNM+is
before_build:
  - nuget restore ".\Server\src\Palla.Labs.Vdt.sln"
build:
  project: .\Server\src\Palla.Labs.Vdt.sln
  verbosity: minimal
test_script:
- ps: >-
    .\Server\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""Server\src\Palla.Labs.Vdt.WebApi.Testes\bin\$env:CONFIGURATION\Palla.Labs.Vdt.WebApi.Testes.dll""" -filter:"+[Palla*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "Server\src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor